baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "AynSight Site"
theme = "PaperMod"

[params]
  defaultTheme = "Light"    # or "dark"
  ShowReadingTime = true
  ShowbreadCrumbs = true
  ShowPostNavLinks = true